export const levelMeta = {
  N5: { label: 'N5 · Sơ cấp I', color: '#22c55e', range: [1, 25], available: true },
  N4: { label: 'N4 · Sơ cấp II', color: '#0ea5e9', range: [26, 50], available: true },
  N3: { label: 'N3 · Trung cấp', color: '#8b5cf6', range: [0, 0], available: true },
  N2: { label: 'N2 · Sắp có', color: '#f59e0b', range: [0, 0], available: false },
  N1: { label: 'N1 · Sắp có', color: '#ef4444', range: [0, 0], available: false },
} as const;

export type LevelId = keyof typeof levelMeta;

export const minnaLessonTitles: Record<number, string> = {
  1: 'はじめまして',
  2: 'これから　お世話に',
  3: 'これを　ください',
  4: 'そちらは　何時まで',
  5: 'この電車は　甲子園へ',
  6: 'いっしょに　行きませんか',
  7: 'いらっしゃい',
  8: 'そろそろ　失礼します',
  9: '残念ですが',
  10: 'ナンプラー、ありますか',
  11: 'これ、お願いします',
  12: '祇園祭は　どうでした',
  13: '別々に　お願いします',
  14: 'みどり町まで',
  15: 'ご家族は？',
  16: '使い方を　教えて',
  17: 'どう　しましたか？',
  18: '趣味は　何ですか',
  19: 'ダイエットは　あした',
  20: 'いっしょに　行かない？',
  21: 'わたしも　そう　思います',
  22: 'どんな　部屋を',
  23: 'どうやって　行きますか',
  24: '手伝いに　行きましょうか',
  25: 'お世話に　なりました',
  26: 'ごみは　どこに',
  27: '何でも　作れるんですね',
  28: '出張も　多いし…',
  29: '忘れ物を　して',
  30: '非常袋を　準備して',
  31: '料理を　習おうと',
  32: '無理を　しない　ほうが',
  33: 'どういう　意味ですか',
  34: 'したとおりに　して',
  35: 'どこか　いい　所',
  36: '毎日　運動するように',
  37: '金閣寺は　14世紀に',
  38: '片づけるのが　好き',
  39: '遅れて、すみません',
  40: '友達が　できたか',
  41: 'ご結婚　おめでとう',
  42: 'ボーナスは　何に',
  43: '毎日　楽しそうです',
  44: 'この写真みたいに',
  45: 'まちがえた　場合は',
  46: '直して　もらった　ばかり',
  47: '婚約したそうです',
  48: '休ませて　いただけませんか',
  49: 'よろしく　お伝え',
  50: '心から　感謝いたします',
};

export const n3Modules = [
  { id: 'vocab', title: 'Từ vựng Mimikara', icon: '📖', total: 880, endpoint: '/vocab', progressKey: 'vocabMastered' },
  { id: 'grammar', title: 'Ngữ pháp N3', icon: '✏️', total: 110, endpoint: '/grammar', progressKey: 'grammarMastered' },
  { id: 'reading', title: 'Đọc hiểu N3', icon: '📝', total: 72, endpoint: '/reading', progressKey: 'readingMastered' },
  { id: 'listening', title: 'Nghe hiểu N3', icon: '🎧', total: 28, endpoint: '/listening', progressKey: 'listeningMastered' },
  { id: 'kanji', title: 'Kanji N3', icon: '漢字', total: 168, endpoint: '/kanji', progressKey: 'kanjiMastered' },
  { id: 'kanjill', title: 'Kanji Look & Learn', icon: '📘', total: 512, endpoint: '/kanjill', progressKey: 'kanjiMastered' },
] as const;

export const resourceCards = [
  { title: 'Thông tin phòng thi JLPT', body: 'Tổng hợp giấy tờ, thời gian, lưu ý phòng thi và chiến thuật trước ngày thi.' },
  { title: 'Tài liệu N3 trọng điểm', body: 'Từ vựng, ngữ pháp, đọc hiểu, nghe hiểu và Kanji theo lộ trình JLPT Hub.' },
  { title: 'Mẹo phân bổ thời gian', body: 'Làm phần dễ trước, đánh dấu câu nghi ngờ, giữ nhịp ổn định ở phần đọc/nghe.' },
];
